# Generated by Django 3.0.11 on 2020-12-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
